version: "3"
services:
  dev:
    build: .
    environment:
      - DISPLAY=$DISPLAY
    network_mode: "host"
    volumes:
      - .:/home/ubuntu
      - $HOME/.Xauthority:/home/ubuntu/.Xauthority
    tty: true
    stdin_open: true
    command: ["bash"]
